-- MediAlert schema
-- Run this in Supabase SQL Editor.

begin;

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  medicine text not null,
  time text not null check (time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  notes text default '',
  active boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'taken', 'missed')),
  taken_time text check (taken_time is null or taken_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  medicine text not null,
  scheduled_time text not null check (scheduled_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  taken_time text check (taken_time is null or taken_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  status text not null check (status in ('taken', 'missed')),
  date date not null default current_date,
  trigger text not null check (trigger in ('box_opened', 'button', 'no_response'))
);

create index if not exists idx_reminders_active_time on public.reminders (active, time);
create index if not exists idx_history_date_id on public.history (date desc, id desc);
create index if not exists idx_history_status on public.history (status);

alter table public.reminders enable row level security;
alter table public.history enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'reminders'
      and policyname = 'Allow public read/write reminders'
  ) then
    create policy "Allow public read/write reminders"
      on public.reminders
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'history'
      and policyname = 'Allow public read/write history'
  ) then
    create policy "Allow public read/write history"
      on public.history
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end $$;

commit;